AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 112
  Exclude:
    - 'config/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
