AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'

Style/BlockComments:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 112
  Exclude:
    - 'config/**/*'
